version: "3.7"

networks:
    app-network:
        driver: bridge

services:
    gateway:
        build: 
            context: ./apps/gateway/
            dockerfile: Dockerfile
        image: laravel8-php-fpm-80
        container_name: gateway
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes: 
            - ./apps/gateway:/var/www
        networks: 
            - app-network
    app1:
        build: 
            context: ./apps/app1/
            dockerfile: Dockerfile
        image: laravel8-php-fpm-80
        container_name: app1
        restart: unless-stopped
        tty: true
        working_dir: /var/www
        volumes: 
            - ./apps/app1:/var/www
        networks: 
            - app-network
    
    mysql:
        image: mysql:5.7.33
        container_name: mysql
        restart: unless-stopped
        tty: true
        environment: 
            MYSQL_DATABASE: laravel8
            MYSQL_ROOT_PASSWORD: 123456
            MYSQL_PASSWORD: 123456
            MYSQL_USER: laravel8
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes: 
            - ./mysql/data:/var/lib/mysql
        networks:
            - app-network
    
    nginx:
        image: nginx:1.19.8-alpine
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports: 
            - 8100:80
        volumes: 
            - ./apps/gateway:/var/www
            - ./nginx/conf:/etc/nginx/conf.d
        networks: 
            - app-network

    redis:
        image: redis:6.2.1-buster
        container_name: redis
        restart: unless-stopped
        tty: true
        volumes: 
            - ./redis/data:/data
        networks: 
            - app-network